version: "3"

tasks:
  reboot:
    cmds:
      - rm -rf pb_data
      - go run . serve
  start:
    cmds:
      - templ generate
      - go run . serve
  watch_templ:
    cmds:
      - templ generate --watch --proxy="http://localhost:8090"
  watch_pb:
    cmds:
      - air serve
  watch_all:
    deps: [watch_pb,watch_templ]
    cmds:
      - echo "watching pb and templ"
